import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { GetServerSideProps } from "next";
import { useTranslation } from "next-i18next";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: {
      ...(await serverSideTranslations(context.locale ?? "en", ["common"])),
    },
  };
};

export default function Home() {
  const router = useRouter();

  const { t } = useTranslation(["common"]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>{t("header")}</h1>

        {["bg", "en"].map((locale) => (
          <button
            key={locale}
            className={styles.card}
            onClick={() => {
              document.cookie = `NEXT_LOCALE=${locale};path=/`;

              router.push(
                { pathname: router.pathname, query: router.query },
                router.asPath,
                {
                  locale,
                },
              );
            }}
          >
            {locale}
          </button>
        ))}
      </main>
    </>
  );
}
